---
tags: [security,javascript,rest,oauth]
projects: [spring-security,spring-security-oauth,spring-boot]
---
:toc: left
:icons: font
:source-highlighter: prettify
:image-width: 500
:doctype: book
:star: {asterisk}
:all: {asterisk}{asterisk}

= Social Login with Spring Boot and OAuth 2.0

This guide shows you how to build a sample app doing various things with "social login" using https://tools.ietf.org/html/rfc6749[OAuth 2.0] and https://projects.spring.io/spring-boot/[Spring Boot].

It starts with a simple, single-provider single-sign on, and works up to a client with a choice of authentication providers:
https://github.com/settings/developers[GitHub] or https://developers.google.com/identity/protocols/OpenIDConnect[Google].

The samples are all single-page apps using Spring Boot and Spring Security on the back end.
They also all use plain https://jquery.org/[jQuery] on the front end.
But, the changes needed to convert to a different JavaScript framework or to use server-side rendering would be minimal.

All samples are implemented using the native OAuth 2.0 support in https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security-oauth2[Spring Boot].

include::overview.adoc[]

include::simple/README.adoc[leveloffset=+1]
include::click/README.adoc[leveloffset=+1]
include::logout/README.adoc[leveloffset=+1]
include::two-providers/README.adoc[leveloffset=+1]
include::custom-error/README.adoc[leveloffset=+1]

== Conclusion

We have seen how to use Spring Boot and Spring Security to build apps in a number of styles with very little effort.
The main theme running through all of the samples is authentication using an external OAuth 2.0 provider.

All of the sample apps can be easily extended and re-configured for more specific use cases, usually with nothing more than a configuration file change.
Remember if you use versions of the samples in your own servers to register with GitHub (or similar) and get client credentials for your own host addresses.
And remember not to put those credentials in source control!

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
