[[_social_login_logout]]
= Add a Logout Button

In this section we modify the <<_social_login_click,click>> app we
built by adding a button that allows the user to log out of the
app. This seems like a simple feature, but it requires a bit of care
to implement, so it's worth spending some time discussing exactly how
to do it. Most of the changes are to do with the fact that we are
transforming the app from a read-only resource to a read-write one
(logging out requires a state change), so the same changes would be
needed in any realistic application that wasn't just static content.

== Client Side Changes

On the client we just need to provide a logout button and some
JavaScript to call back to the server to ask for the authentication to
be cancelled. First, in the "authenticated" section of the UI, we add
the button:

.index.html
----
<div class="container" ng-show="home.authenticated">
  Logged in as: <span ng-bind="home.user"></span>
  <div>
    <button ng-click="home.logout()" class="btn btn-primary">Logout</button>
  </div>
</div>
----

and then we provide the `logout()` function that it refers to in the
JavaScript:

.index.html
----
angular
  .module("app", [])
  .controller("home", function($http, $location) {
    var self = this;
    self.logout = function() {
      $http.post('/logout', {}).success(function() {
        self.authenticated = false;
        $location.path("/");
      }).error(function(data) {
        console.log("Logout failed")
        self.authenticated = false;
      });
    };
  });
----

The `logout()` function does a POST to `/logout` and then clears the
`authenticated` flag. Now we can switch over to the server side to
implement that endpoint.

== Adding a Logout Endpoint

Spring Security has built in support for a `/logout` endpoint which
will do the right thing for us (clear the session and invalidate the
cookie). To configure the endpoint we simply extend the existing
`configure()` method in our `WebSecurityConfigurer`:

.SocialApplication.java
[source,java]
----
@Override
protected void configure(HttpSecurity http) throws Exception {
  http.antMatcher("/**")
    ... // existing code here
    .and().logout().logoutSuccessUrl("/").permitAll();
}
----

The `/logout` endpoint requires us to POST to it, and to protect the
user from Cross Site Request Forgery (CSRF, pronounced "sea surf"), it
requires a token to be included in the request. The value of the token
is linked to the current session, which is what provides the
protection, so we need a way to get that data into our JavaScript app.

AngularJS also has built in support for CSRF (they call it XSRF), but
it is implemented in a slightly different way than the out-of-the box
behaviour of Spring Security. What Angular would like is for the
server to send it a cookie called "XSRF-TOKEN" and if it sees that, it
will send the value back as a header named "X-XSRF-TOKEN". To teach
Spring Security about this we need to add a filter that creates the
cookie and also we need to tell the existing CRSF filter about the
header name. In the `WebSecurityConfigurer`:

.SocialApplication.java
[source,java]
----
@Override
protected void configure(HttpSecurity http) throws Exception {
  http.antMatcher("/**")
    ... // existing code here
    .and().csrf().csrfTokenRepository(csrfTokenRepository())
    .and().addFilterAfter(csrfHeaderFilter(), CsrfFilter.class);
}
----

where the `csrfHeaderFilter()` is a custom filter:

.SocialApplication.java
[source,java]
----
private Filter csrfHeaderFilter() {
  return new OncePerRequestFilter() {
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
        FilterChain filterChain) throws ServletException, IOExeption {
      CsrfToken csrf = (CsrfToken) request.getAttribute(CsrfToken.class.getName());
      if (csrf != null) {
        Cookie cookie = WebUtils.getCookie(request, "XSRF-TOKEN");
        String token = csrf.getToken();
        if (cookie == null || token != null && !token.equals(cookie.getValue())) {
          cookie = new Cookie("XSRF-TOKEN", token);
          cookie.setPath("/");
          response.addCookie(cookie);
        }
      }
      filterChain.doFilter(request, response);
    }
  };
}
----

and the `csrfTokenRepository()` is defined here:

.SocialApplication.java
[source,java]
----
private CsrfTokenRepository csrfTokenRepository() {
  HttpSessionCsrfTokenRepository repository = new HttpSessionCsrfTokenRepository();
  repository.setHeaderName("X-XSRF-TOKEN");
  return repository;
}
----

== Ready To Roll!

With those changes in place we are ready to run the app and try out
the new logout button. Start the app and load the home page in a new
browser window. Click on the "login" link to take you to Facebook (if
you are already logged in there you might not notice the
redirect). Click on the "Logout" button to cancel the current session
and return the app to the unauthenticated state. If you are curious
you should be able to see the new cookies and headers in the requests
that the browser exchanges with the local server.

Remember that now the logout endpoint is working with the browser
client, then all other HTTP requests (POST, PUT, DELETE, etc.) will
also work just as well. So this should be a good platform for an
application with some more realistic features.